include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = ResultsConverter/ AdunShell/
GNUSTEP_INSTALLATION_DOMAIN=USER

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

