include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = Analyse/ Results/ Controllers/
ADDITIONAL_INCLUDE_DIRS += -I$(GNUSTEP_HOME)/$(GNUSTEP_USER_HEADERS)

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

