
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS =  Frameworks/ Languages/ Modules/ 
GNUSTEP_INSTALLATION_DOMAIN=USER

#Rpm

PACKAGE_NAME=StepTalk
PACKAGE_VERSION=0.13

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

